# Generated by Django 6.0.2 on 2026-02-14 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageUrl', models.ImageField(upload_to='offers/')),
                ('offers_badge', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('price1', models.CharField(max_length=50)),
                ('price2', models.CharField(max_length=50)),
                ('button_text', models.CharField(max_length=50)),
            ],
        ),
    ]
