# Generated by Django 6.0.2 on 2026-02-14 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_offers'),
    ]

    operations = [
        migrations.AddField(
            model_name='offers',
            name='stock_text',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='offers',
            name='price1',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='offers',
            name='price2',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
