# Generated by Django 6.0.2 on 2026-02-26 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_newarrivals'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cloths',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageUrl', models.ImageField(upload_to='cloths/')),
                ('name', models.CharField(max_length=150)),
                ('price', models.CharField(blank=True, max_length=50)),
                ('desccription', models.TextField()),
                ('price1', models.CharField(blank=True, max_length=50)),
                ('price2', models.CharField(blank=True, max_length=50)),
                ('discount_text', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
