# Generated by Django 6.0.2 on 2026-02-28 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Toy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('educational', 'Educational'), ('outdoor', 'Outdoor'), ('creative', 'Creative'), ('electronic', 'Electronic'), ('plush', 'Plush'), ('building', 'Building')], max_length=50)),
                ('age_range', models.CharField(choices=[('0-2', '0-2 years'), ('3-5', '3-5 years'), ('6-8', '6-8 years'), ('9-12', '9-12 years'), ('13+', '13+ years')], max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('imageUrl', models.ImageField(upload_to='toys/')),
                ('is_bestseller', models.BooleanField(default=False)),
                ('is_new', models.BooleanField(default=False)),
                ('rating', models.DecimalField(decimal_places=1, default=5.0, max_digits=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
