# Generated by Django 6.0.2 on 2026-03-09 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_cart_cartitem_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloths',
            name='subcategory',
            field=models.CharField(blank=True, choices=[('', 'None'), ('dresses', 'Dresses'), ('tops', 'Tops'), ('pants', 'Pants'), ('skirts', 'Skirts'), ('shirts', 'Shirts'), ('shoes', 'Shoes'), ('accessories', 'Accessories')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='cloths',
            name='category',
            field=models.CharField(choices=[('kids-men', 'Kids Boys'), ('men', 'Men'), ('women', 'Women'), ('kids-girl', 'Kids Girls')], default='kids-men', max_length=15),
        ),
    ]
