# Generated by Django 6.0.2 on 2026-03-10 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_productreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloths',
            name='care_instructions',
            field=models.TextField(blank=True, default='', help_text='Washing and care instructions'),
        ),
        migrations.AddField(
            model_name='cloths',
            name='features',
            field=models.TextField(blank=True, default='', help_text='Key features, one per line'),
        ),
        migrations.AddField(
            model_name='cloths',
            name='long_description',
            field=models.TextField(blank=True, default='', help_text='Detailed description shown on the product detail page'),
        ),
        migrations.AddField(
            model_name='cloths',
            name='material',
            field=models.CharField(blank=True, default='', help_text='e.g. 100% Cotton, Polyester blend', max_length=200),
        ),
        migrations.AddField(
            model_name='cloths',
            name='sizes_available',
            field=models.CharField(blank=True, default='', help_text='e.g. S, M, L, XL or 2T, 3T, 4T', max_length=200),
        ),
        migrations.AddField(
            model_name='newarrivals',
            name='features',
            field=models.TextField(blank=True, default='', help_text='Key features, one per line'),
        ),
        migrations.AddField(
            model_name='newarrivals',
            name='long_description',
            field=models.TextField(blank=True, default='', help_text='Detailed description shown on the product detail page'),
        ),
        migrations.AddField(
            model_name='newarrivals',
            name='material',
            field=models.CharField(blank=True, default='', help_text='e.g. 100% Cotton, Polyester blend', max_length=200),
        ),
        migrations.AddField(
            model_name='offers',
            name='features',
            field=models.TextField(blank=True, default='', help_text='Key features, one per line'),
        ),
        migrations.AddField(
            model_name='offers',
            name='long_description',
            field=models.TextField(blank=True, default='', help_text='Detailed description shown on the product detail page'),
        ),
        migrations.AddField(
            model_name='offers',
            name='material',
            field=models.CharField(blank=True, default='', help_text='e.g. 100% Cotton, Polyester blend', max_length=200),
        ),
        migrations.AddField(
            model_name='toy',
            name='dimensions',
            field=models.CharField(blank=True, default='', help_text='e.g. 30cm x 20cm x 15cm', max_length=200),
        ),
        migrations.AddField(
            model_name='toy',
            name='features',
            field=models.TextField(blank=True, default='', help_text='Key features, one per line'),
        ),
        migrations.AddField(
            model_name='toy',
            name='long_description',
            field=models.TextField(blank=True, default='', help_text='Detailed description shown on the product detail page'),
        ),
        migrations.AddField(
            model_name='toy',
            name='material',
            field=models.CharField(blank=True, default='', help_text='e.g. Wood, Plastic, Plush fabric', max_length=200),
        ),
        migrations.AddField(
            model_name='toy',
            name='safety_info',
            field=models.TextField(blank=True, default='', help_text='Safety certifications and age warnings'),
        ),
    ]
