# Generated by Django 6.0.2 on 2026-03-28 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_newarrivals_stock_quantity_offers_stock_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloths',
            name='brand',
            field=models.CharField(blank=True, default='', help_text='Brand or collection name', max_length=150),
        ),
        migrations.AddField(
            model_name='newarrivals',
            name='brand',
            field=models.CharField(blank=True, default='', help_text='Brand or collection name', max_length=150),
        ),
        migrations.AddField(
            model_name='offers',
            name='brand',
            field=models.CharField(blank=True, default='', help_text='Brand or collection name', max_length=150),
        ),
        migrations.AddField(
            model_name='toy',
            name='brand',
            field=models.CharField(blank=True, default='', help_text='Brand or collection name', max_length=150),
        ),
    ]
