# Generated by Django 6.0.2 on 2026-03-28 07:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_cloths_brand_newarrivals_brand_offers_brand_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('price_drop', 'Price Drop'), ('back_in_stock', 'Back in Stock'), ('price_threshold', 'Threshold Reached')], max_length=20)),
                ('old_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('new_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_drop_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_sent', models.BooleanField(default=False, help_text='Whether notification was sent to user')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('user_viewed', models.BooleanField(default=False)),
                ('user_purchased', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Price Alert',
                'verbose_name_plural': 'Price Alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WishlistShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_token', models.CharField(help_text='Unique token for sharing link', max_length=32, unique=True)),
                ('share_url', models.URLField(blank=True, help_text='Public URL for accessing shared wishlist')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('revoked', 'Revoked')], default='active', max_length=10)),
                ('allow_comments', models.BooleanField(default=False, help_text='Allow viewers to comment')),
                ('allow_suggestions', models.BooleanField(default=True, help_text='Allow viewers to suggest items')),
                ('show_prices', models.BooleanField(default=True, help_text='Display prices in shared wishlist')),
                ('show_created_dates', models.BooleanField(default=True, help_text='Show when items were added')),
                ('expires_at', models.DateTimeField(blank=True, help_text='When shared link expires', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('view_count', models.IntegerField(default=0, help_text='Number of times shared wishlist was viewed')),
                ('last_viewed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Wishlist Share',
                'verbose_name_plural': 'Wishlist Shares',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='wishlistitem',
            name='alert_threshold_percent',
            field=models.IntegerField(default=10, help_text='Alert if price drops by this percentage (default 10%)'),
        ),
        migrations.AddField(
            model_name='wishlistitem',
            name='is_shared',
            field=models.BooleanField(default=False, help_text='Include in public/shared wishlist'),
        ),
        migrations.AddField(
            model_name='wishlistitem',
            name='last_alert_sent',
            field=models.DateTimeField(blank=True, help_text='Last time price alert was sent for this item', null=True),
        ),
        migrations.AddField(
            model_name='wishlistitem',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price when item was added to wishlist', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='wishlistitem',
            name='price_alert_enabled',
            field=models.BooleanField(default=False, help_text='Send notification when price drops'),
        ),
        migrations.AddField(
            model_name='wishlistitem',
            name='shared_at',
            field=models.DateTimeField(blank=True, help_text='When wishlist was made public', null=True),
        ),
        migrations.AddIndex(
            model_name='wishlistitem',
            index=models.Index(fields=['user', 'price_alert_enabled'], name='myapp_wishl_user_id_b5fa5d_idx'),
        ),
        migrations.AddIndex(
            model_name='wishlistitem',
            index=models.Index(fields=['price_alert_enabled', 'last_alert_sent'], name='myapp_wishl_price_a_a21e63_idx'),
        ),
        migrations.AddField(
            model_name='pricealert',
            name='wishlist_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_alerts', to='myapp.wishlistitem'),
        ),
        migrations.AddField(
            model_name='wishlistshare',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_wishlists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='pricealert',
            index=models.Index(fields=['is_sent', 'wishlist_item'], name='myapp_price_is_sent_31162e_idx'),
        ),
        migrations.AddIndex(
            model_name='pricealert',
            index=models.Index(fields=['alert_type', 'created_at'], name='myapp_price_alert_t_ad8360_idx'),
        ),
    ]
